### ISSUE TITLE
"No Form Fills saved.  You can add one in your Vault"

### ISSUE THREAD

**Issue by paul-shannon** [PriceLab/interactionNetworks#10]
![image](https://user-images.githubusercontent.com/2480712/42042812-ce2cdf44-7aa9-11e8-81af-df7d53573c27.png)
@oshah97   can we disable this?

**Comment by oshah97** [comment]
Checking on it.

**Comment by oshah97** [comment]
That issue doesn't seem to be popping up on my end!
