### ISSUE TITLE
Additions and issues - entryApp

### ISSUE THREAD

**Issue by oshah97** [PriceLab/interactionNetworks#13]
@paul-shannon 

1. I added two new items on the isbStaffList, Sean Gibbons and Intern Group (changed pushed). 

2. Addition of email function that allows user to enter interactions they've had over email. Looking into to adding a simple radio button and a way to add that information to the existing data frame.

3. Time and date do not automatically update to the users time and date. They seem to be fixed to the time and date of the last build (6/29, 9:54 am).

![image](https://user-images.githubusercontent.com/29240354/42182986-feaa4be0-7df4-11e8-947d-df8362bc7756.png)

Let me know what you think!

**Comment by paul-shannon** [comment]
Maybe make the time and date output widgets reactive to other inputs (see below) so that it is constantly updated?

  - page load
  - any event on the UI

**Comment by oshah97** [comment]
@paul-shannon 
Updates:
- added radio button (email vs. in person) and ability to distinguish between them in the file name ("...interaction.RData" vs. "...emailInteraction.RData")
- addition of "Current time" button, which should navigate around the issue of Sys.time() and Sys.Date() not updating for the user. 
- Same issue fixed (hopefully) for the calendar date
- Small changes to intern list and isb staff list
